// The App's cross-language fixture is generated by `scripts/sample-flush.mjs`
// from these same modules. Keep the two in step: if capture changes shape, the
// committed bytes have to be regenerated (the failure message says how).

import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";

const FIXTURE = new URL("../../app/Tests/WatchLogsKitTests/Fixtures/extension-flush.json", import.meta.url);
const SCRIPT = new URL("../scripts/sample-flush.mjs", import.meta.url);

test("the committed Flush fixture is what the capture modules produce today", () => {
  const generated = execFileSync(process.execPath, [SCRIPT.pathname], { encoding: "utf8" });
  assert.equal(
    generated,
    readFileSync(FIXTURE, "utf8"),
    "regenerate with: node scripts/sample-flush.mjs > ../app/Tests/WatchLogsKitTests/Fixtures/extension-flush.json",
  );
});
