import Foundation
import Testing
@testable import WatchLogsKit

/// The other half of the seam, in the other language: bytes the Extension's own
/// capture modules produced, ingested by the real server and turned into Watched
/// time.
///
/// The fixture is generated by `extension/scripts/sample-flush.mjs` from
/// `extension/src/capture.js`, and the extension's `test/fixture.test.js` fails
/// if the committed bytes drift from what those modules produce. So a change to
/// either side that breaks the wire contract fails on one side or the other.
@Suite("Extension capture over the wire", .serialized)
struct ExtensionCaptureTests {
    /// 21 s watched in the foreground, then 9 s of Background audio, then `nav`.
    private let range = DateRange(startMs: 1_788_026_000_000, endMs: 1_788_027_000_000)

    /// Read from the source tree rather than a bundled resource: the fixture is
    /// generated across the repo, and `#filePath` keeps the two paths adjacent.
    private func fixture() throws -> Data {
        let path = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures/extension-flush.json")
        return try Data(contentsOf: path)
    }

    @Test("a Flush the Extension really built is accepted and Ack'd whole")
    func accepted() throws {
        let (service, client, _) = try LoopbackServerTests.makeService()
        defer { service.stop() }

        let response = try client.send(
            method: "POST",
            path: "/v1/flush",
            headers: [
                "Authorization": "Bearer \(service.pairing().token)",
                "Content-Type": "application/json",
            ],
            body: try fixture()
        )

        #expect(response.status == 200)
        let views = try #require(response.json()?["views"] as? [[String: Any]])
        #expect(views.count == 1)
        #expect(views[0]["viewId"] as? String == "9f2a1c04-11d2-4a55-9b3e-6c1f0e8a7d40")
        #expect(views[0]["ackSeq"] as? Int == 11)
    }

    @Test("the captured Events become 21 s of Watched time and 9 s of Background audio")
    func totals() throws {
        let (service, client, store) = try LoopbackServerTests.makeService()
        defer { service.stop() }

        _ = try client.send(
            method: "POST",
            path: "/v1/flush",
            headers: [
                "Authorization": "Bearer \(service.pairing().token)",
                "Content-Type": "application/json",
            ],
            body: try fixture()
        )

        let totals = try store.totals(in: range)
        #expect(totals.watchedSeconds == 21)
        #expect(totals.backgroundSeconds == 9)
        #expect(WatchedTimeLine.duration(milliseconds: totals.watchedMs) == "21s")
    }
}
